name: first_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.7
  pie_chart: ^5.0.0
  intl: 0.17.0
  english_words: ^4.0.0
  shared_preferences: ^2.0.5
  idb_shim: ^2.0.0
  charts_flutter: ^0.12.0
  collection: ^1.15.0
  fluttertoast: ^8.0.8
  sqflite_common_ffi: ^2.3.2+1
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true